---
# .github/ISSUE_TEMPLATE/config.yml

blank_issues_enabled: false
contact_links:
  - name: polyglot-relay Community Support
    url: https://github.com/JuanVilla424/polyglot-relay/discussions
    about: Please ask and answer questions here.
  - name: polyglot-relay Security Reports
    url: https://github.com/JuanVilla424/polyglot-relay/blob/main/SECURITY.md
    about: Please report security vulnerabilities here.
