import tomllib
from pathlib import Path

DISCORD_MESSAGE_LIMIT = 2000

PYPROJECT_PATH = Path(__file__).resolve().parent.parent / "pyproject.toml"
DEPLOY_SHA_PATH = Path(__file__).resolve().parent.parent / "deploy_sha.txt"
DEPLOY_COMMIT_LOG_PATH = Path(__file__).resolve().parent.parent / "deploy_commit_log.txt"


def get_current_version() -> str | None:
    """Return the version in this image's pyproject.toml, or None if unreadable.

    Cosmetic only -- shown alongside the deploy SHA for human context, no
    longer what decides whether a deploy gets announced (see get_deploy_sha).
    """
    if not PYPROJECT_PATH.exists():
        return None
    try:
        with open(PYPROJECT_PATH, "rb") as f:
            data = tomllib.load(f)
        return data["tool"]["poetry"]["version"]
    except (KeyError, tomllib.TOMLDecodeError):
        return None


def get_deploy_sha() -> str | None:
    """Return the git commit SHA baked into this image at build time, or None.

    Generated by deploy.sh (git rev-parse HEAD > deploy_sha.txt) right before
    the Docker build, since .git itself is never copied into the image.
    """
    if not DEPLOY_SHA_PATH.exists():
        return None
    sha = DEPLOY_SHA_PATH.read_text(encoding="utf-8").strip()
    return sha or None


def get_deploy_commit_log() -> list[str]:
    """Return the "<full-sha> <subject>" lines baked in by deploy.sh, newest first.

    Empty if the file is missing (e.g. a build done without deploy.sh).
    """
    if not DEPLOY_COMMIT_LOG_PATH.exists():
        return []
    return [
        line
        for line in DEPLOY_COMMIT_LOG_PATH.read_text(encoding="utf-8").splitlines()
        if line.strip()
    ]


def commits_since(last_sha: str | None, commit_log: list[str]) -> list[str]:
    """Commits newer than last_sha, newest first.

    If last_sha is None or isn't in the log (a deploy older than the log's
    window), returns the whole log as the best available approximation --
    there's no way to know the true boundary in that case.
    """
    if last_sha is None:
        return commit_log
    for index, line in enumerate(commit_log):
        if line.startswith(last_sha):
            return commit_log[:index]
    return commit_log


def _split_into_chunks(text: str, first_budget: int, budget: int) -> list[str]:
    """Split text into chunks at line boundaries, so a commit line is never cut mid-line.

    The first chunk gets a smaller budget since it shares a message with the header.
    """
    chunks: list[str] = []
    current: list[str] = []
    current_len = 0
    limit = first_budget
    for line in text.splitlines():
        line_len = len(line) + 1  # + the newline that joins it to the next line
        if current and current_len + line_len > limit:
            chunks.append("\n".join(current))
            current = []
            current_len = 0
            limit = budget
        current.append(line)
        current_len += line_len
    if current:
        chunks.append("\n".join(current))
    return chunks


def build_deploy_announcement(
    sha: str, pyproject_version: str | None, new_commits: list[str]
) -> list[str]:
    """Format the deploy announcement as one or more Discord messages.

    Commits are split across multiple messages at line boundaries instead of
    being truncated -- nothing about what changed is ever silently dropped
    just because it doesn't fit in one 2000-char Discord message.
    """
    version_suffix = f" (v{pyproject_version})" if pyproject_version else ""
    header = f"🚀 Deployed `{sha[:7]}`{version_suffix}"
    if not new_commits:
        return [f"{header}\n_(no new commits found -- deployed the same code again)_"]

    body = "\n".join(new_commits)
    chunks = _split_into_chunks(
        body,
        first_budget=DISCORD_MESSAGE_LIMIT - len(header) - 2,
        budget=DISCORD_MESSAGE_LIMIT,
    )
    return [f"{header}\n\n{chunks[0]}"] + chunks[1:]
